use crate::api::client::RoverClient;
use rover_proto::v1::{
    AppDetailResponse, AppSummary, DeployEvent, LogEntry, ServerInfo, ServerMetrics,
};
use std::sync::Arc;
use tokio::sync::Mutex;

#[derive(Debug, Clone)]
pub enum Message {
    Navigate(crate::Screen),
    Tick,
    Noop,
    SetAddressInput(String),
    SetTokenInput(String),
    SetProfileName(String),
    Connect,
    ConnectWithKey(String, String),
    ConnectionSuccess(Arc<Mutex<RoverClient>>, String),
    ConnectionError(String),
    Disconnect,
    DeleteProfile(String),
    Refresh,
    RefreshApps,
    DataRefreshed(Box<ServerInfo>, Box<ServerMetrics>),
    AppsRefreshed(Vec<AppSummary>),
    SelectApp(String),
    AppDetailLoaded(Box<AppDetailResponse>),
    LogLinesReceived(Vec<String>),
    StartApp(String),
    StopApp(String),
    RestartApp(String),
    DeleteApp(String),
    Deploy,
    SubmitDeploy,
    DeployComplete,
    DeployStreamDone(Vec<rover_proto::v1::deploy_event::Event>),
    DeployError(String),
    SetDeployName(String),
    SetDeployBuildCmd(String),
    SetDeployRunCmd(String),
    SetDeployRuntime(String),
    SetDeploySourcePath(String),
    PickSourceDirectory,
    SetDeployEnvKey(String),
    SetDeployEnvValue(String),
    AddDeployEnvVar,
    RemoveDeployEnvVar(usize),
    SetEnvKey(String),
    SetEnvValue(String),
    SetEnvSecret(bool),
    AddEnvVar,
    EnvVarAdded(Box<AppDetailResponse>),
    SaveProfile(String, String),
    DismissToast(usize),
    ToastError(String),
    ToastInfo(String),
    RetryConnect,
    SetTerminalInput(String),
    SendTerminalInput,
    TerminalOutput(String),
    LoadLogs,
    ConfirmDelete((String, String)),
    CancelDelete,
    ExecuteDelete(String),
    RefreshLogs,
}
