use crate::api::client::RoverClient;
use std::sync::Arc;
use tokio::sync::Mutex;

pub type ClientRef = Arc<Mutex<RoverClient>>;

#[derive(Debug, Clone)]
pub enum Message {
    Noop,
    Tick,
    Select(usize),
    ShowAdd,
    HideAdd,
    SetAddr(String),
    SetToken(String),
    SetName(String),
    Connect,
    DevAdded(String, ClientRef, String),
    DevAddErr(String),
    DevConnected(u32, Option<ClientRef>),
    DevError(u32, String),
    Refresh,
    RefreshApps,
    Data(
        Box<rover_proto::v1::ServerInfo>,
        Box<rover_proto::v1::ServerMetrics>,
    ),
    Apps(Vec<rover_proto::v1::AppSummary>),
    SelectApp(String),
    Detail(Box<rover_proto::v1::AppDetailResponse>),
    Logs(Vec<String>),
    Back,
    Start(String),
    Stop(String),
    Restart(String),
    Delete(String),
    CancelDelete,
    ConfirmDelete((String, String)),
    OpenDeploy,
    CloseDeploy,
    SetDName(String),
    SetDRuntime(String),
    SetDBuild(String),
    SetDRun(String),
    SetDPath(String),
    PickPath,
    SetDEKey(String),
    SetDEValue(String),
    AddDEVar,
    RemoveDEVar(usize),
    SubmitDeploy,
    DeployDone(Vec<rover_proto::v1::DeployEvent>),
    DeployErr(String),
    SetEKey(String),
    SetEValue(String),
    AddEnv,
    Toast(String),
    Dismiss(usize),
}
